language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm
  - hhvm-nightly
cache:
  directories:
    - vendor
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly
notifications:
  irc: "irc.freenode.org##atoum"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bcb8350326a64f8fd270
    on_success: change
    on_failure: always
    on_start: never
env:
    global:
        - secure: "vJ1TnFhU9muqLwkiBd13lFqdPJIrwKJ5OJjR3/jQROWQsRO4NPd/I7OfdDKk\noJGYbgjGMw7bmBYI0xjhYfZAnrClwIBvn1Qx5x5UDGxTHC8ZP6xs49AGa37I\n7BJlWC7+nRwPmmLhoLsbut/O7Kkn8IkdJIeChHbdn8RHQIJTJ4Y="
sudo: false
before_script:
  - "[[ \"$TRAVIS_PHP_VERSION\" != '5.3' && \"$TRAVIS_PHP_VERSION\" != '5.4' ]] && composer require 'atoum/reports-extension:^2.0.1' || true"
  - "cp resources/configurations/ci/.travis.php.dist .atoum.php"
script:
  - bin/atoum +verbose
  - mkdir ../phar
  - php -n -dphar.readonly=Off scripts/phar/generator.php -d ../phar
  - php -n -ddate.timezone=Europe/Paris ../phar/atoum.phar --test-it -ncc +verbose -c .atoum.php
deploy:
  provider: releases
  api_key:
    secure: lmt12noTXqP/X7a71FffP/lIJR+9sX6vrE7gIdTHroMqfxh2x3u8w1NBs3+npa9lq00Fi2UZiWJY7BurdsTokM75ZqXZAjlC42KCZGLiXKMQZcei5nOdKhKWZ06FSVMFlxf6dhknsMgJjeNmDGVSXhDnN2ZuPnf68may/o/nLaA=
  file: ../phar/atoum.phar
  skip_cleanup: true
  on:
    tags: true
