build: false
shallow_clone: true
platform: 'x86'
clone_folder: C:\projects\atoum

environment:
  matrix:
    - PHP_DOWNLOAD_FILE: https://windows.php.net/downloads/releases/archives/php-5.6.40-nts-Win32-VC11-x86.zip
    - PHP_DOWNLOAD_FILE: https://windows.php.net/downloads/releases/latest/php-7.1-nts-Win32-VC14-x86-latest.zip
    - PHP_DOWNLOAD_FILE: https://windows.php.net/downloads/releases/latest/php-7.2-nts-Win32-VC15-x86-latest.zip
    - PHP_DOWNLOAD_FILE: https://windows.php.net/downloads/releases/latest/php-7.3-nts-Win32-VC15-x86-latest.zip

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/46967a83f6bd0cd3b7ea
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

cache:
  - c:\php -> appveyor.yml
  - '%LOCALAPPDATA%\Composer'

init:
  - SET PATH=C:\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1

install:
  - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
  - cd c:\php
  - IF %PHP%==1 curl --location --output php.zip %PHP_DOWNLOAD_FILE%
  - IF %PHP%==1 7z x php.zip -y > 7z.log
  - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
  - curl --location --output composer.phar https://getcomposer.org/composer.phar
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - cd c:\projects\atoum
#  - php c:\php\composer.phar require --ignore-platform-reqs atoum/telemetry-extension:^1.0.0
  - copy resources\configurations\ci\.appveyor.php.dist .atoum.php

test_script:
  - cd C:\projects\atoum
  - php bin\atoum +verbose
